---
# tasks file for dockerd

  - name: Add docker Repo
    yum_repository:
      name: "{{ docker_repo_name }}"
      description: "{{ docker_repo_description }}"
      baseurl: "{{ docker_fedora_repo }}"
      async: yes
      enabled: yes
      state: present 

  - name: Install required rpms
    dnf:
      state: latest
      name: 
        - dnf-plugins-core
        - docker-ce
    notify:
      - start and enable docker
